2017-08-22 11:37:55 jdbc[11]: exception
org.h2.jdbc.JdbcSQLException: Table "ALF_CONTENT_URL" not found; SQL statement:
DROP TABLE alf_content_url [42102-190]
2017-08-22 11:37:55 jdbc[11]: exception
org.h2.jdbc.JdbcSQLException: Table "ACT_RU_TASK" not found; SQL statement:
select min(id_) from ACT_RU_TASK [42102-190]
2017-08-22 11:38:11 jdbc[10]: exception
org.h2.jdbc.JdbcSQLException: Value too long for column "REPORT VARCHAR(1024)": "STRINGDECODE('07220005 org.alfresco.error.AlfrescoRuntimeException: 07220004 Bootstrap failed\n\tat org.alfresco.repo.importer.I... (6051)"; SQL statement:
insert into alf_applied_patch
            (
                id, description,
                fixes_from_schema, fixes_to_schema, target_schema,
                applied_to_schema, applied_on_date, applied_to_server,
                was_executed, succeeded, report
            )
            values
            (
                ?, ?,
                ?, ?, ?,
                ?, ?, ?,
                ?, ?, ?
            ) [22001-190]
2017-08-22 13:15:56 jdbc[10]: exception
org.h2.jdbc.JdbcSQLException: Value too long for column "REPORT VARCHAR(1024)": "STRINGDECODE('07220003 org.alfresco.error.AlfrescoRuntimeException: 07220002 Bootstrap failed\n\tat org.alfresco.repo.importer.I... (6053)"; SQL statement:
insert into alf_applied_patch
            (
                id, description,
                fixes_from_schema, fixes_to_schema, target_schema,
                applied_to_schema, applied_on_date, applied_to_server,
                was_executed, succeeded, report
            )
            values
            (
                ?, ?,
                ?, ?, ?,
                ?, ?, ?,
                ?, ?, ?
            ) [22001-190]
2017-08-22 13:19:39 jdbc[10]: exception
org.h2.jdbc.JdbcSQLException: Value too long for column "REPORT VARCHAR(1024)": "STRINGDECODE('07220003 org.alfresco.error.AlfrescoRuntimeException: 07220002 Bootstrap failed\n\tat org.alfresco.repo.importer.I... (6051)"; SQL statement:
insert into alf_applied_patch
            (
                id, description,
                fixes_from_schema, fixes_to_schema, target_schema,
                applied_to_schema, applied_on_date, applied_to_server,
                was_executed, succeeded, report
            )
            values
            (
                ?, ?,
                ?, ?, ?,
                ?, ?, ?,
                ?, ?, ?
            ) [22001-190]
2017-08-22 13:30:42 jdbc[10]: exception
org.h2.jdbc.JdbcSQLException: Value too long for column "REPORT VARCHAR(1024)": "STRINGDECODE('07220003 org.alfresco.error.AlfrescoRuntimeException: 07220002 Bootstrap failed\n\tat org.alfresco.repo.importer.I... (6045)"; SQL statement:
insert into alf_applied_patch
            (
                id, description,
                fixes_from_schema, fixes_to_schema, target_schema,
                applied_to_schema, applied_on_date, applied_to_server,
                was_executed, succeeded, report
            )
            values
            (
                ?, ?,
                ?, ?, ?,
                ?, ?, ?,
                ?, ?, ?
            ) [22001-190]
2017-08-22 13:31:56 jdbc[10]: exception
org.h2.jdbc.JdbcSQLException: Value too long for column "REPORT VARCHAR(1024)": "STRINGDECODE('07220003 org.alfresco.error.AlfrescoRuntimeException: 07220002 Bootstrap failed\n\tat org.alfresco.repo.importer.I... (6173)"; SQL statement:
insert into alf_applied_patch
            (
                id, description,
                fixes_from_schema, fixes_to_schema, target_schema,
                applied_to_schema, applied_on_date, applied_to_server,
                was_executed, succeeded, report
            )
            values
            (
                ?, ?,
                ?, ?, ?,
                ?, ?, ?,
                ?, ?, ?
            ) [22001-190]
2017-08-22 13:44:24 jdbc[15]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-190]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:118)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.pool.impl.GenericObjectPool.addObject(GenericObjectPool.java:1691)
	at org.apache.commons.pool.impl.GenericObjectPool.ensureMinIdle(GenericObjectPool.java:1648)
	at org.apache.commons.pool.impl.GenericObjectPool.access$700(GenericObjectPool.java:192)
	at org.apache.commons.pool.impl.GenericObjectPool$Evictor.run(GenericObjectPool.java:1784)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 15 more
2017-08-22 15:11:15 jdbc[15]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-190]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:118)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.pool.impl.GenericObjectPool.addObject(GenericObjectPool.java:1691)
	at org.apache.commons.pool.impl.GenericObjectPool.ensureMinIdle(GenericObjectPool.java:1648)
	at org.apache.commons.pool.impl.GenericObjectPool.access$700(GenericObjectPool.java:192)
	at org.apache.commons.pool.impl.GenericObjectPool$Evictor.run(GenericObjectPool.java:1784)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 15 more
2017-08-22 16:53:48 jdbc[15]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-190]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:118)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.pool.impl.GenericObjectPool.addObject(GenericObjectPool.java:1691)
	at org.apache.commons.pool.impl.GenericObjectPool.ensureMinIdle(GenericObjectPool.java:1648)
	at org.apache.commons.pool.impl.GenericObjectPool.access$700(GenericObjectPool.java:192)
	at org.apache.commons.pool.impl.GenericObjectPool$Evictor.run(GenericObjectPool.java:1784)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 15 more
